### ISSUE TITLE
Enable release configuration and build type CI legs for the SDK and fix any issues

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-for-c#1110]
- [x] Fix all warnings and issues from building the SDK in release - https://github.com/Azure/azure-sdk-for-c/issues/1111
- [ ] Update code coverage CI leg to not fail in release builds (either by not running code coverage with a console message OR running it with a warning message) - https://github.com/Azure/azure-sdk-for-c/issues/1112
- [ ] Enable the release configuration in the CI matrix - https://github.com/Azure/azure-sdk-for-c/issues/1113

**Comment by ahsonkhan** [comment]
This is a necessary step before enabling the map file generation. See https://github.com/Azure/azure-sdk-for-c/issues/240 and https://github.com/Azure/azure-sdk-for-c/pull/956
