### ISSUE TITLE
Release KeyVault library alpha preview 1 for C

### ISSUE THREAD

**Issue by gilbertw** [Azure/azure-sdk-for-c#215]
This tracks the work required to ship a first alpha preview (name TBD)

January Milestone
- [x] Set exact release date and name

Features
- [x] Azure.Core
   - [x] Policies
- [x] Azure.Identity
- [x] Azure.KeyVault.Keys

Optionally if time permits
- [x] Azure.Storage.Blobs

Testing
- [ ] TODO: Define testing min bar

Release Activities
- [ ] Compliance
  - [ ] TODO: Identify compliance requirements
- [ ] vcpkg
  - [ ] Build vcpkg
- [ ] Full API review
