### ISSUE TITLE
Bootstrap azure-sdk-for-c repo

### ISSUE THREAD

**Issue by joshfree** [Azure/azure-sdk-for-c#4]
**Design Guidelines**
- [x] Get C99 SDK DRAFT Design Guidelines reviewed and committed to azure-sdk repo (@JeffreyRichter, @GorNishanov)

**3rd Party Dependencies**
- [x] Investigate Package Management Strategy
- [x] Define 3rd Party Library Dependencies (libuv, libcurl, etc)
   - [x] Logging infrastructure https://github.com/Azure/azure-sdk-for-c/issues/61
   - [x] libcurl / httpclient stack https://github.com/Azure/azure-sdk-for-c/issues/63
   - [x] XML Serialization stack https://github.com/Azure/azure-sdk-for-c/issues/62
   - [x] JSON Serialization stack
- [x] Investigate ThreadX stack (@jhendrixMSFT)

**Infrastructure**
- [x] Create initial cmake build system (@sergey-shandar, @vhvb1989)
- [x] Initial check-in enabling first set of clang check styles rules (@sergey-shandar, @vhvb1989)
- [x] Setup initial CI system (@sergey-shandar)
- [x] Investigate unit test framework 

**Azure.Core**
- [x] Define Exchange data types (@sergey-shandar)
- [x] Design some type of span/slice data type
- [x] Design some type of tagged union / discriminated union type
- [x] Define HTTP Request Builder (URL, Path, Query Parameters, Headers, Body) (@vhvb1989, @sergey-shandar, @gilbertw, @JeffreyRichter) 
- [x] Define HTTP Response Parser (Headers, Body)
- [x] Define URI Parser / Builder
- [x] Define HTTP Pipeline Design Pattern (@gilbertw)
- [x] Define HTTP Pipeline Policies (Retry, Telemetry, Logging, Tracing, Authentication, Request ID) (@gilbertw)
   - [x] Define level of customer configuration of Policies

**Platforms**
- [x] Windows (build, test, CI)
- [x] Linux (build, test, CI)
- [x] Investigate RTOS ThreadX, FreeRTOS, etc (build, test, CI) 
- [x] MacOS (build, test, CI)

**Comment by gilbertw** [comment]
Initial bootstrap is complete
