### ISSUE TITLE
Azure.Core technical debt

### ISSUE THREAD

**Issue by sergey-shandar** [Azure/azure-sdk-for-c#41]
- [ ] proper parser for IEEE double numbers (@sergey-shandar) #45
- [ ] CMakeList.txt warnings @barcharcraz #49
- [x] 100 vs 120 column width (@antkmsft).
- [ ] clang-format: figure out how to get rid of alignment when multi-line initializing `x = { ... }` (@antkmsft, @sergey-shandar) #48
- [ ] conventions for `in/out`, `out` and other pointer parameters and variables (@antkmsft, @barcharcraz) #46 
- [x] `az_config.h` to suppress warnings (@barcharcraz).
- [ ] doxygen (@barcharcraz). #47
