### ISSUE TITLE
Create Azure.Identity

### ISSUE THREAD

**Issue by gilbertw** [Azure/azure-sdk-for-c#56]
Create the identity library 

Azure.Identity (antkmsft)
- [x] Define types of authentication that are in scope, initially
   - Device code
   - Implicit Grant
- [x] Define AuthenticationClient and public APIs
- [x] Implement proposed API including underlying private classes
- [x] Create unit and integration tests

**Comment by antkmsft** [comment]
If we are ever to close this, I think we're currently satisfied with the identity features we have now.
