### ISSUE TITLE
Release preview JSON builder/parser

### ISSUE THREAD

**Issue by gilbertw** [Azure/azure-sdk-for-c#570]
API Design
- [x] Design Parser functionality
- [x] Design Builder functionality

Features

- [x] Add Features

Doc Improvement:

- [ ] Document usage patterns

**Comment by ahsonkhan** [comment]
Closing this epic. Tracking the leftover documentation component with this issue: https://github.com/Azure/azure-sdk-for-c/issues/903
